In [60]:
#coding:utf-8
"""
Edited on Fri Mar 22 10:20:32 2019

@author: zhang
"""

from keras.layers import Dense, Conv1D, BatchNormalization, MaxPooling1D, Activation, Flatten
from keras.models import Sequential
from keras.utils import plot_model
from keras.regularizers import l2
import preprocess_real
from keras.callbacks import TensorBoard
import numpy as np

# 训练参数
batch_size = 128
epochs = 4
num_classes = 4
length = 1024
BatchNorm = True # 是否批量归一化
number = 1000 # 每类样本的数量
normal = True # 是否标准化
rate = [0.7,0.2,0.1] # 测试集验证集划分比例


path = r'C:\Users\86132\Desktop\train_new'


x_train, y_train, x_valid, y_valid, x_test, y_test = preprocess_real.prepro(d_path=path,length=length,
                                                                  number=number,
                                                                  normal=normal,
                                                                  rate=rate,
                                                                  enc=True, 
                                                                  enc_step=14,
                                                                  featrue='DE_time'  )






{'B1.csv': array([-0.07000954, -0.08040539,  0.25648507, ...,  0.01949222,
        0.03297433,  0.06546136]), 'B10.csv': array([-0.09486212, -0.19947034, -0.02095413, ...,  0.16535896,
        0.19378511,  0.05555281]), 'B101.csv': array([-0.11516651,  0.10850667,  0.08917689, ...,  0.01770543,
        0.12523749, -0.02712667]), 'B108.csv': array([ 0.05977613, -0.00536036,  0.0693598 , ..., -0.18761257,
       -0.04174583,  0.10996858]), 'B18.csv': array([-0.00097461,  0.04921784,  0.08040539, ..., -0.02241605,
       -0.00779689, -0.02111657]), 'B26.csv': array([-0.06822275,  0.05035489, -0.00763445, ..., -0.08950176,
        0.05555281,  0.08674036]), 'B28.csv': array([-0.32941844,  0.3342915 ,  0.32308347, ...,  0.15285146,
       -0.03719764, -0.03589816]), 'B35.csv': array([-0.04320774, -0.05165437, -0.03037537, ...,  0.00048731,
        0.05035489,  0.14001908]), 'B38.csv': array([-0.10980615,  0.08901445,  0.2469014 , ..., -0.00373601,
        0.28523609, -0.21798794]), 'B56.csv

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [3]:

import sys, matplotlib, sklearn, IPython
import numpy as np, pandas as pd, scipy as sp

modules = {'NumPy': np, 'pandas': pd, 'scikit-learn': sklearn,
           'scipy': sp, 'matplotlib': matplotlib, 'IPython': IPython,'tensorflow':tensorflow,'keras':keras}

print('Python version: %s' % (sys.version))
for i in modules.items():
    print('{} version: {}'.format(i[0], i[1].__version__))

NameError: name 'tensorflow' is not defined

In [305]:
#以下是关于RF的失败尝试
y = np.argmax(y_valid_1, axis=1)  # 从 oneshot转变为一维数组

x3 = []
for i in range(x_valid_1.shape[0]):
    x3.append(np.mean(x_valid_1[i]))  #取每行的平均值作为特征

x4 = []
for i in range(x_valid_2.shape[0]):
    x4.append(np.mean(x_valid_2[i]))

x3 = np.array(x3)  #数组转numpy

x4 = np.array(x4) 

xx = np.vstack((x3,x4)) #纵向numpy拼接

xx = xx.T  #numpy矩阵转置

In [309]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

parameter_grid = {'n_estimators': [5, 10, 25, 50],
                  'criterion': ['gini', 'entropy'],
                  'max_features': [1, 2, 3, 4],
                  'warm_start': [True, False]}

# skf = StratifiedKFold(n_splits=10)
# cross_validation = skf.get_n_splits(all_inputs, all_classes)

# grid_search = GridSearchCV(random_forest_classifier,
#                            param_grid=parameter_grid,
#                            cv=cross_validation)

rf.fit(x, label)
print('Best score: {}'.format(rf.score(xx,y)))


Best score: 0.5525


In [226]:
#将两个特征组合成一个数组
#数据深度拼接
x_train = np.dstack((x_train_1,x_train_2))
x_valid = np.dstack((x_valid_1,x_valid_2))
x_test = np.dstack((x_test_1,x_test_2))

In [227]:
y_train = y_train_1
y_valid = y_valid_1
y_test = y_test_1

In [61]:
x_train, x_valid, x_test = x_train[:,:,np.newaxis], x_valid[:,:,np.newaxis], x_test[:,:,np.newaxis]   #如果使用两个特征，则注释这一行
# 输入数据的维度
input_shape =x_train.shape[1:]

print("输入数据的维度：",input_shape)

print('训练样本维度:', x_train.shape)
print(x_train.shape[0], '训练样本个数')
print('验证样本的维度', x_valid.shape)
print(x_valid.shape[0], '验证样本个数')
print('测试样本的维度', x_test.shape)
print(x_test.shape[0], '测试样本个数')

model_name = "cnn_1D"

# 实例化一个Sequential
model = Sequential()

#第一层卷积
model.add(Conv1D(filters=64, kernel_size=20, strides=8, padding='same',kernel_regularizer=l2(1e-4), input_shape=input_shape))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling1D(pool_size=4, strides=4, padding='valid'))


# 从卷积到全连接需要展平
model.add(Flatten())

# 添加全连接层
model.add(Dense(units=100, activation='relu', kernel_regularizer=l2(1e-4)))
# 增加输出层，共num_classes个单元
model.add(Dense(units=num_classes, activation='softmax', kernel_regularizer=l2(1e-4)))


# 编译模型
model.compile(optimizer='Adam', loss='categorical_crossentropy',
              metrics=['accuracy'])

# TensorBoard调用查看一下训练情况
tb_cb = TensorBoard(log_dir='logs/{}'.format(model_name))

# 开始模型训练
model.fit(x=x_train, y=y_train, batch_size=batch_size, epochs=epochs,
          verbose=1, validation_data=(x_valid, y_valid), shuffle=True,
          callbacks=[tb_cb])

# 评估模型
score = model.evaluate(x=x_test, y=y_test, verbose=0)
print("测试集上的损失率：", score[0])
print("测试集上的准确率：", score[1])
# plot_model(model=model, to_file='cnn-1D.png', show_shapes=True)


输入数据的维度： (1024, 1)
训练样本维度: (99400, 1024, 1)
99400 训练样本个数
验证样本的维度 (28400, 1024, 1)
28400 验证样本个数
测试样本的维度 (14200, 1024, 1)
14200 测试样本个数
Train on 99400 samples, validate on 28400 samples
Epoch 1/4
99400/99400 [==============================] - 105s 1ms/step - loss: 0.0887 - accuracy: 0.9790 - val_loss: 0.0575 - val_accuracy: 0.9842
Epoch 2/4
99400/99400 [==============================] - 74s 747us/step - loss: 0.0184 - accuracy: 0.9993 - val_loss: 0.0139 - val_accuracy: 1.0000
Epoch 3/4
99400/99400 [==============================] - 64s 648us/step - loss: 0.0122 - accuracy: 1.0000 - val_loss: 0.0103 - val_accuracy: 1.0000
Epoch 4/4
99400/99400 [==============================] - 62s 628us/step - loss: 0.0134 - accuracy: 0.9989 - val_loss: 0.0091 - val_accuracy: 1.0000
测试集上的损失率： 0.00912288139823457
测试集上的准确率： 1.0


In [62]:
#模型的保存与调用
print("Saving model to disk \n")
mp = r"C:\Users\86132\Desktop\ipython\model.model"
model.save(mp)

Saving model to disk 



In [4]:
    # 模型的加载及使用
    from keras.models import load_model
    print("Using loaded model to predict...")
    load_model = load_model(r"C:\Users\86132\Desktop\ipython\model.model")
    np.set_printoptions(precision=4)
    unknown = x_test
    predicted = load_model.predict(unknown)
    print("Using model to predict species for features: ")
    print(unknown)
    print("\nPredicted softmax vector is: ")
    print(predicted)

Using loaded model to predict...
Using model to predict species for features: 
[[[-1.7585]
  [-1.8044]
  [-1.2104]
  ...
  [ 1.9708]
  [ 0.6784]
  [-0.041 ]]

 [[ 0.3579]
  [ 0.785 ]
  [ 0.9498]
  ...
  [-0.1521]
  [ 0.073 ]
  [ 0.0852]]

 [[-1.0492]
  [ 0.1073]
  [ 2.9781]
  ...
  [ 0.4476]
  [ 1.2218]
  [-0.2756]]

 ...

 [[ 0.9359]
  [ 0.1415]
  [-0.1245]
  ...
  [-0.229 ]
  [ 0.1971]
  [ 0.1016]]

 [[-0.234 ]
  [-0.1026]
  [-0.8314]
  ...
  [-1.2747]
  [-0.1145]
  [-0.7473]]

 [[ 0.7769]
  [-0.6955]
  [ 0.252 ]
  ...
  [-0.4721]
  [ 0.2351]
  [-0.4345]]]

Predicted softmax vector is: 
[[3.3512e-07 1.3538e-08 1.2723e-05 9.9999e-01]
 [9.7395e-01 2.4653e-02 4.5933e-06 1.3948e-03]
 [4.4601e-07 1.2275e-05 3.1930e-02 9.6806e-01]
 ...
 [3.3226e-05 7.7235e-03 8.2369e-01 1.6855e-01]
 [9.9919e-07 6.0055e-05 3.3256e-02 9.6668e-01]
 [1.8504e-05 3.8474e-01 5.3284e-01 8.2406e-02]]


In [53]:
model.predict(x=x_test)

array([[6.1578639e-03, 8.2942420e-01, 1.3359456e-01, 3.0823428e-02],
       [6.6255208e-04, 9.4556904e-01, 4.4254500e-02, 9.5140142e-03],
       [9.8842938e-05, 4.7883852e-03, 8.8268274e-01, 1.1243000e-01],
       ...,
       [5.8667373e-04, 6.2326086e-04, 2.3850940e-01, 7.6028061e-01],
       [1.6605077e-09, 3.0348233e-06, 9.9997544e-01, 2.1595582e-05],
       [2.8994857e-10, 2.6156842e-05, 9.9139833e-01, 8.5755540e-03]],
      dtype=float32)

In [160]:
from sklearn.metrics import classification_report
y_true = np.argmax(y_test, axis=1)
y_pred = np.argmax(model.predict(x=x_test,verbose=0), axis=1)
target_name = ['0','1','2','3']
print(classification_report(y_true, y_pred, target_names = target_name))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       600
           2       1.00      1.00      1.00      1400
           3       1.00      1.00      1.00       600

    accuracy                           1.00      2800
   macro avg       1.00      1.00      1.00      2800
weighted avg       1.00      1.00      1.00      2800



In [61]:
x_test

array([[[ 0.36424188],
        [-0.80417574],
        [-0.34602297],
        ...,
        [-0.60295296],
        [-0.83176511],
        [ 0.74268604]],

       [[-0.25449087],
        [-0.16965791],
        [ 0.15100285],
        ...,
        [ 0.20383509],
        [ 0.18675822],
        [ 0.45072339]],

       [[ 1.63113083],
        [-0.31561337],
        [-1.84087848],
        ...,
        [ 0.42571237],
        [-0.55628203],
        [ 0.02932747]],

       ...,

       [[ 0.15113216],
        [ 0.46302014],
        [ 0.34620302],
        ...,
        [ 0.1552334 ],
        [-0.87124112],
        [ 0.02384659]],

       [[ 0.10951902],
        [ 0.02086097],
        [-0.13948859],
        ...,
        [ 0.33822932],
        [-0.14751439],
        [-0.14606092]],

       [[-0.26605008],
        [-0.25551406],
        [-0.3506406 ],
        ...,
        [-0.25048505],
        [-0.12416836],
        [-0.23333351]]])

In [3]:
    def capture(original_path):
        
        """读取mat文件，返回字典

        :param original_path: 读取路径
        :return: 数据字典
        """
        files = {}
        for i in filenames:
            # 文件路径
            file_path = os.path.join(original_path, i)
            with open(file_path) as f:
                reader = pd.read_csv(f)
                v = reader.loc[:, 'DE_time'].values
                files.update({i: v})
            #     file = defaultdict(list)
            #     for row in reader:
            #         for k, v in row.items():
            #             file[k].append(v)
            # #file = loadmat(file_path)
            #
            # file_keys = file.keys()
            # print(file)
            # for key in file_keys:
            #     if 'FE' in key:
            #         files[i] = file[key].ravel()
        return files

In [4]:
#将测试集窗口化
def slice_enc(data,slice_rate=0): 
        """将数据切分为前面多少比例，后面多少比例.

        :param data: 单挑数据
        :param slice_rate: 验证集以及测试集所占的比例
        :return: 切分好的数据
        """
        length=1024
        enc=True
        enc_step=14
        keys = data.keys()
        Train_Samples = {}
        Test_Samples = {}
        for i in keys:
            number = len(data[i])//14
            slice_data = data[i]
            all_lenght = len(slice_data)
            end_index = int(all_lenght * (1 - slice_rate))
            samp_train = int(number * (1 - slice_rate))  # 700
            Train_sample = []
            Test_Sample = []
            if enc:
                enc_time = length // enc_step
                samp_step = 0  # 用来计数Train采样次数
                for j in range(samp_train):
#                     print("end_index"+str(end_index))
#                     print('length'+str(length))
                    random_start = np.random.randint(low=0, high=(end_index - 2 * length))
                    label = 0
                    for h in range(enc_time):
                        samp_step += 1
                        random_start += enc_step
                        sample = slice_data[random_start: random_start + length]
                        Train_sample.append(sample)
                        if samp_step == samp_train:
                            label = 1
                            break
                    if label:
                        break
            else:
                for j in range(samp_train):
                    random_start = np.random.randint(low=0, high=(end_index - length))
                    sample = slice_data[random_start:random_start + length]
                    Train_sample.append(sample)

            # 抓取测试数据
            for h in range(number - samp_train):
                random_start = np.random.randint(low=end_index, high=(all_lenght - length))
                sample = slice_data[random_start:random_start + length]
                Test_Sample.append(sample)
            Train_Samples[i] = Train_sample
            Test_Samples[i] = Test_Sample
        return Train_Samples, Test_Samples

In [5]:
    # 仅抽样完成，打标签
    def add_labels(train_test):
        X = []
        Y = []
        label = 0
        for i in filenames:
            if 'N' in i:
                label = 0
            elif 'B' in i:
                label = 1
            elif 'IR' in i:
                label = 3
            elif 'OR' in i:
                label = 2
            x = train_test[i]
            X += x
            lenx = len(x)
            Y += [i] * lenx
        print(Y)
        return X, Y


In [6]:
    def scalar_stand(Train_X, Test_X):
        # 用训练集标准差标准化训练集以及测试集
        scalar = preprocessing.StandardScaler().fit(Train_X)
        Train_X = scalar.transform(Train_X)
        Test_X = scalar.transform(Test_X)
        return Train_X, Test_X

In [7]:
import numpy as np
import os
import pandas as pd  # 读取csv储存为字典
from collections import defaultdict
from sklearn import preprocessing  # 0-1编码
from sklearn.model_selection import StratifiedShuffleSplit  # 随机划分，保证每一类比例相同

In [8]:
original_path=r'C:\Users\86132\Desktop\data'
filenames = os.listdir(original_path)
data = capture(original_path)
    # 将数据切分为训练集、测试集
train, test = slice_enc(data)
    # 为训练集制作标签，返回X，Y
Train_X, Train_Y = add_labels(train)
scalar = preprocessing.StandardScaler().fit(Train_X)
Train_X = scalar.transform(Train_X)

['TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv', 'TEST1.csv'

In [34]:
Train_X = Train_X.reshape(35950, 1024,1)

In [9]:
Train_X.shape

(35950, 1024)

In [36]:
file_name = []
for i in range(len(Train_Y)):
    file_name.append(os.path.splitext(Train_Y[i])[0])

In [65]:
Train_X.reshape(35950, 1024)

array([[-0.18000295,  0.09916478,  0.20272113, ..., -0.48757482,
        -0.58225518, -0.41322683],
       [-0.03398177, -0.34544686, -0.65850387, ...,  0.13639831,
         0.29301007,  0.16938387],
       [-0.36634342, -0.17461086,  0.15922491, ..., -0.08606168,
        -0.211784  , -0.19692174],
       ...,
       [-0.08410844,  0.03017332,  0.23534328, ..., -0.01009973,
        -0.2139505 , -0.17409557],
       [-0.05032742, -0.03334263, -0.17460851, ...,  0.18631616,
         0.2540131 , -0.00344281],
       [-0.04052003,  0.0225076 ,  0.22229442, ..., -0.11753163,
        -0.36993836, -0.40344419]])

In [13]:
df = pd.DataFrame(Train_X.reshape(35950, 1024))
df = df.iloc[0:50,:]

In [14]:
df.to_csv('test_phm.csv')

In [15]:
df.values

array([[ 0.46313345,  0.11295484,  0.01161068, ...,  0.17785097,
         0.19570096,  0.01732117],
       [-0.03628524,  0.2535839 ,  0.47268941, ..., -0.22004033,
        -0.22506859,  0.00424403],
       [ 0.49290012,  0.4071941 ,  0.34297695, ..., -0.01674614,
         0.19796926,  0.12520754],
       ...,
       [ 0.08939628,  0.0512944 ,  0.19364412, ..., -0.55487782,
        -0.6174844 , -0.44146836],
       [ 0.93719534,  1.11466645,  1.0002594 , ..., -0.17111927,
         0.12198123,  0.18623418],
       [ 0.45651863,  0.31308081,  0.32008652, ...,  0.24525332,
         0.271689  ,  0.42053287]])

In [51]:
pre_x = model.predict(x=Train_X, verbose=0)

In [52]:
pre_x

array([[9.6409768e-01, 4.1703524e-06, 8.2842982e-04, 3.5069749e-02],
       [8.2514149e-01, 2.8612487e-06, 2.1876211e-03, 1.7266801e-01],
       [9.8993659e-01, 7.1533674e-07, 4.4815466e-04, 9.6144369e-03],
       ...,
       [9.4566655e-01, 1.9195668e-06, 1.5180454e-03, 5.2813496e-02],
       [9.5350444e-01, 4.8147112e-06, 1.3000628e-03, 4.5190625e-02],
       [9.8311299e-01, 2.3909163e-06, 7.1783579e-04, 1.6166847e-02]],
      dtype=float32)

In [53]:
predict_label = np.argmax(pre_x, axis=1)
predict_label    

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [54]:
df = pd.DataFrame()

In [55]:
df['label']=predict_label

In [56]:
df

label
0          0
1          0
2          0
3          0
4          0
...      ...
35945      0
35946      0
35947      0
35948      0
35949      0

[35950 rows x 1 columns]

In [57]:
df['filename']=file_name

In [58]:
df.describe()

label
count  35950.000000
mean       0.558720
std        0.990813
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        3.000000

In [59]:
df.to_csv("17_041444_2017210106.csv",index = 0)

In [26]:
df = pd.read_csv("17_0414_2017210106.csv")

In [27]:
df.describe()

label
count  35950.000000
mean       0.731266
std        1.211354
min        0.000000
25%        0.000000
50%        0.000000
75%        2.000000
max        3.000000

In [7]:
df.to_csv("17_0414_2017210106.csv",index = 0)